# 
# Setup
title:              Ambica
tagline:             'My First Blog'
description:         'Made with R-ladies SF'
url:                 https://github.com/gravity-seven/gravity-seven.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ambica
  url:               
  email:             ambica.nd@gmail.com

# Custom vars
version:             1.0.0
